import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

// The language list is shared with the pages (src/i18n/config.ts) and the scripts.
const languages = JSON.parse(readFileSync(new URL('./src/i18n/languages.json', import.meta.url), 'utf8'));
const siteUrl = readFileSync(new URL('./src/data/site.ts', import.meta.url), 'utf8').match(/url: '([^']+)'/)[1];
const [defaultLocale, ...otherLocales] = Object.keys(languages);
const htmlLang = Object.fromEntries(Object.entries(languages).map(([code, l]) => [code, l.htmlLang]));

/**
 * Writes Netlify's _redirects so a first visit lands on the visitor's language at the edge, with no flash:
 *   /install/  /pt-br/install/  302!  Language=pt
 * Netlify reads the browser's Accept-Language, and lets an `nf_lang` cookie override it. The language
 * switcher sets that cookie, so an explicit choice always wins. Crawlers send no Accept-Language and get English.
 */
const languageRedirects = () => ({
  name: 'language-redirects',
  hooks: {
    'astro:build:done': ({ dir, pages }) => {
      const others = otherLocales;
      const isLocalized = (p) => others.some((l) => p === `${l}/` || p.startsWith(`${l}/`));
      const english = pages.map((p) => p.pathname).filter((p) => !isLocalized(p) && !p.startsWith('404'));
      const lines = ['# Generated by astro.config.mjs at build time. Do not edit.'];
      for (const l of others) {
        for (const p of english) lines.push(`/${p}  /${l}/${p}  302!  Language=${languages[l].match.join(',')}`);
        lines.push(`/${l}/*  /${l}/404/index.html  404`);
      }
      lines.push('/*  /404/index.html  404');
      writeFileSync(fileURLToPath(new URL('_redirects', dir)), lines.join('\n') + '\n');
    },
  },
});

export default defineConfig({
  site: siteUrl,
  trailingSlash: 'always',
  i18n: { defaultLocale, locales: Object.keys(languages), routing: { prefixDefaultLocale: false } },
  integrations: [
    sitemap({ i18n: { defaultLocale, locales: htmlLang }, filter: (page) => !page.includes('/404') }),
    languageRedirects(),
  ],
  vite: { plugins: [tailwindcss()] },
  build: { inlineStylesheets: 'auto' },
});
