// Derives the color tokens from a few decisions (hues, one lightness per role) and prints the CSS.
// For every hue it finds the highest chroma that still fits sRGB at the role's lightness, then caps it, so all
// hues carry the same visual weight. Run with --write to replace the block between the PALETTE markers in
// src/styles/global.css, then `npm run check:colors`.   See docs/color-study.md.
import { readFileSync, writeFileSync } from 'node:fs';
import { clampChroma } from 'culori';

// One hue per subject, sampled from the terminal colors of the tools themselves (tclock's red digits, ghpending's
// amber repo headers, the Omarchy panel's blue, and so on). Green is not a subject: it is the one action color.
export const hues = { red: 27, orange: 52, amber: 80, teal: 190, blue: 250, violet: 288, rose: 350 };
const ACTION = 150; // phosphor green: tclock's "all systems healthy" dot, and Evangelion Unit-01's green on its purple
const NEUTRAL = 310; // dark aubergine purple. ai-memory's ground is indigo (282), ai-jail's is maroon (355); this sits between

const fit = (l, c, h) => { const k = clampChroma({ mode: 'oklch', l, c, h }, 'oklch'); return `oklch(${l} ${Math.min(c, k.c).toFixed(3)} ${h})`; };
const roles = {
  light: { ink: [0.48, 0.16], soft: [0.955, 0.035] },
  dark: { ink: [0.83, 0.13], soft: [0.27, 0.055] },
};
// Signal colors, the same in both themes, never used for text: rules, dots, bars, glows.
const vivid = { red: [0.65, 0.23], orange: [0.74, 0.18], amber: [0.84, 0.17], teal: [0.8, 0.13], blue: [0.7, 0.17], violet: [0.57, 0.22], rose: [0.7, 0.2] };

const neutrals = {
  light: { bg: [0.983, 0.008], surface: [1, 0], tint: [0.955, 0.016], line: [0.88, 0.028], text: [0.2, 0.045], muted: [0.45, 0.045] },
  dark: { bg: [0.16, 0.05], surface: [0.205, 0.055], tint: [0.24, 0.058], line: [0.35, 0.06], text: [0.96, 0.012], muted: [0.78, 0.035] },
};

function theme(name) {
  const out = [];
  for (const [k, [l, c]] of Object.entries(neutrals[name])) out.push(`  --${k}: ${fit(l, c, NEUTRAL)};`);
  for (const [k, h] of Object.entries(hues)) {
    out.push(`  --${k}: ${fit(...roles[name].ink, h)};`, `  --${k}-soft: ${fit(...roles[name].soft, h)};`);
  }
  out.push(`  --green: ${fit(...roles[name].ink, ACTION)};`);
  return out.join('\n');
}
const shared = [
  ...Object.entries(hues).map(([k, h]) => `  --v-${k}: ${fit(...vivid[k], h)};`),
  `  --ink: ${fit(0.16, 0.05, NEUTRAL)};`, `  --ink-raised: ${fit(0.21, 0.055, NEUTRAL)};`, `  --ink-line: ${fit(0.35, 0.06, NEUTRAL)};`,
  `  --on-ink: ${fit(0.96, 0.012, NEUTRAL)};`, `  --on-ink-muted: ${fit(0.78, 0.035, NEUTRAL)};`,
  `  --veil: oklch(0.16 0.05 ${NEUTRAL} / 0.6);`, `  --shade: oklch(0 0 0 / 0.15);`,
  // Phosphor green is roughly the complement of the purple ground, and nothing decorative uses it,
  // so a single green button is the loudest thing on a page.
  `  --v-green: ${fit(0.85, 0.2, ACTION)};`,
  `  --action: ${fit(0.85, 0.2, ACTION)};`, `  --action-hi: ${fit(0.91, 0.17, ACTION)};`, `  --on-action: ${fit(0.22, 0.05, ACTION + 10)};`,
].join('\n');

const css = `/* PALETTE:START generated by scripts/build-palette.mjs, do not edit by hand */
:root {
${shared}
${theme('light')}
}
[data-theme='dark'] {
${theme('dark')}
}
/* PALETTE:END */`;

if (process.argv.includes('--write')) {
  const file = new URL('../src/styles/global.css', import.meta.url);
  const src = readFileSync(file, 'utf8');
  writeFileSync(file, src.replace(/\/\* PALETTE:START[\s\S]*?PALETTE:END \*\//, css));
  console.log('palette written to src/styles/global.css');
} else console.log(css);
